export const IMPORT_EVENTS_SUCCESS = "IMPORT_EVENTS_SUCCESS";
export const IMPORT_EVENTS_FAIL = "IMPORT_EVENTS_FAIL";
export const TOGGLE_EVENTS_LOADER = "TOGGLE_EVENTS_LOADER";
export const FILTER_EVENTS = "FILTER_EVENTS";
export const TOGGLE_FILTERS = "TOGGLE_FILTERS";
